server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/i2pbridge
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
