server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://62.234.20.70:3306/i2pbridge
    url: jdbc:mysql://localhost:3306/i2pbridge
    username: root
    password: 123456
#    password: yzw123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: date